name: Deploy CoolShade to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (lockfile if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Compute BASE_PATH for GitHub Pages
        shell: bash
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          USER_PAGE="${OWNER}.github.io"
          if [[ "$REPO_NAME" == "$USER_PAGE" ]]; then
            echo "BASE_PATH=/" >> $GITHUB_ENV
          else
            echo "BASE_PATH=/${REPO_NAME}/" >> $GITHUB_ENV
          fi
          echo "Using BASE_PATH=$BASE_PATH"

      - name: Build
        run: npm run build -- --base=${BASE_PATH}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


